spring.application.name=backend
spring.datasource.url=jdbc:postgresql://ep-lively-credit-b315ojaj-pooler.c-4.ap-southeast-1.aws.neon.tech:5432/ecom?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_cqCk6JUrLT1e
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8081
